"use client";
import { FormEvent, useState } from "react";
import Image from "next/image";

export default function AuthPage(){
  const [step,setStep]=useState<"email"|"verify"|"mfa"|"request">("email"); const [email,setEmail]=useState(""); const [error,setError]=useState("");
  function submit(e:FormEvent){e.preventDefault();if(!email.toLowerCase().endsWith("@growwithom.com")){setError("That account is outside Grow With OM.");setStep("request");return}setError("");setStep("verify")}
  return <main className="auth-shell"><section className="auth-card"><a className="auth-brand" href="/"><Image className="logo-light" src="/om-logo-light.svg" alt="OM" width={44} height={30}/><Image className="logo-dark" src="/om-logo-dark.svg" alt="OM" width={44} height={30}/><span>OM One</span></a>{step==="email"&&<><p className="modal-label">WORK ACCESS</p><h1>Come on in.</h1><p>Use your Grow With OM email. This space is for agency work only.</p><form onSubmit={submit}><label>Work email<input autoFocus type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@growwithom.com" required/></label><button>Continue with email</button><div className="or"><span/>or<span/></div><button className="google" type="button" onClick={()=>{setEmail("jason@growwithom.com");setStep("mfa")}}>G&nbsp;&nbsp; Continue with Google</button></form></>}
  {step==="verify"&&<><p className="modal-label">CHECK YOUR INBOX</p><h1>We sent the key.</h1><p>A six-digit verification code is on its way to <b>{email}</b>.</p><div className="code-inputs">{[0,1,2,3,4,5].map(i=><input key={i} inputMode="numeric" maxLength={1} aria-label={`Digit ${i+1}`}/>)}</div><button onClick={()=>setStep("mfa")}>Verify email</button><button className="text-button" onClick={()=>setStep("email")}>Use a different email</button></>}
  {step==="mfa"&&<><p className="modal-label">ONE MORE CHECK</p><h1>Authenticator code</h1><p>Enter the current 6-digit code from Google Authenticator or your TOTP app.</p><label>Authentication code<input className="totp" autoFocus inputMode="numeric" maxLength={6} placeholder="000 000"/></label><a className="primary-link" href="/">Open my dashboard</a><button className="text-button">Use a recovery code</button><div className="trust"><input type="checkbox" id="trust"/><label htmlFor="trust">Trust this device for 30 days</label></div></>}
  {step==="request"&&<><p className="modal-label">APPROVAL REQUIRED</p><h1>Ask to be added.</h1><p>{error} Third-party and guest access needs superadmin approval before sign-in is enabled.</p><label>Email to request<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Why do you need access?<textarea placeholder="Client collaboration, contractor role, or another reason"/></label><button onClick={()=>alert("Request sent to the OM One superadmins.")}>Send access request</button><button className="text-button" onClick={()=>setStep("email")}>Back to sign in</button></>}
  <footer>Read-only by design · Google, Slack and Asana stay the source of truth</footer></section><aside className="auth-aside"><p>OM ONE / DASHBOARD</p><blockquote>What needs you,<br/><em>without the noise.</em></blockquote><span>Your agency work secretary — sharp, calm, and pointed at the real work.</span><div><i/><b>Grow With OM workspace</b><small>Protected access</small></div></aside></main>
}
